// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAil7T00MVx7NN7jYHXROsVWDmiD6fGRw',
    appId: '1:88539640615:web:dd06b901b2ab82119daf02',
    messagingSenderId: '88539640615',
    projectId: 'envirosense-heartbeat',
    authDomain: 'envirosense-heartbeat.firebaseapp.com',
    databaseURL: 'https://envirosense-heartbeat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirosense-heartbeat.firebasestorage.app',
    measurementId: 'G-HKRMW1H1X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-kojo1we0TCulwQtzwUSj5WwJst3dDvo',
    appId: '1:88539640615:android:8c5df3498058ff609daf02',
    messagingSenderId: '88539640615',
    projectId: 'envirosense-heartbeat',
    databaseURL: 'https://envirosense-heartbeat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirosense-heartbeat.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAil7T00MVx7NN7jYHXROsVWDmiD6fGRw',
    appId: '1:88539640615:web:cbb08bcf07ce5a259daf02',
    messagingSenderId: '88539640615',
    projectId: 'envirosense-heartbeat',
    authDomain: 'envirosense-heartbeat.firebaseapp.com',
    databaseURL: 'https://envirosense-heartbeat-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'envirosense-heartbeat.firebasestorage.app',
    measurementId: 'G-K1STRVZPEP',
  );
}
